### ISSUE TITLE
cache WB (Writeback) counter increment when reading cache line and D refill counter when writing into cache line  

### ISSUE THREAD

**Issue by SoCScholar** [SpinalHDL/NaxRiscv#75] opened 2024-01-12 14:24 UTC
Hi Charles,

when performing **reading** operations during the **simulation** and **on FPGA**, `SCOPE_HART_DCACHE_WRITEBACK` counter value is increased, which was not expected.   

#define SCOPE_HART_DCACHE_WRITEBACK(hart)	((hart) * 0x80 + 0x14)	// Read only

I wonder why the WB counter is increased when reading the cache line.  

Reading and writing test operation looks like this         

```
#define TEST_SIZE (1024*1024)	/* 1 MB */

/* test memory region */

char test_memory[TEST_SIZE];


for (char *ptr = &test_memory[0]; ptr < &test_memory[sizeof(test_memory)]; ptr += 64) {  
		char c = '?';
		c = *ptr; // read
		//*ptr = c; // write
		__asm__ volatile("" : : "r"(c) : "memory");
 
	}
```

Here each cache line is size of 64 bytes so we increase the pointer by 64 of char( 1 bytes). I try to read 64 bytes character that reflect each cache line size until 15 KB, 16 KB, and 1MB to see value of L1 D cache WB and L1 D cache refill counter.                             

as L1 cache size is of 16 KB and each cache line size is of 64 Byte, we try to experiment with a 15 KB, 16 KB, and 1MB  test memory size.   

Similarly,

when performing **Write** operations during the **simulation** and **on FPGA**, `SCOPE_HART_DCACHE_REFILL` counter value is increased, which was not expected.   

#define SCOPE_HART_DCACHE_REFILL(hart)		((hart) * 0x80 + 0x10)	// Read only 

I also wonder why the `DCACHE_REFILL` counter is increased when **Writing** into the cache line. 

is there might be a bug  in Spinal HDL while designing the NAX L1 cache architecture?

**Comment by Dolu1990** [comment] 2024-01-15 08:27
Should be fixed with that commit. not a bug in the L1, with coherency, the writeback path is also used to give back permissions, just had to include the dirty flag in the probe

**Comment by Dolu1990** [comment] 2024-01-15 15:22
Ahh my bad, i forgot the pull.
I pushed a fix.

**Comment by Dolu1990** [comment] 2024-01-16 16:40
you want to read a existing counter ? or create a new one ? Which counter exactly ?

**Comment by Dolu1990** [comment] 2024-01-17 15:40
add(l2c.io.down.a.fire && l2c.io.down.a.opcode === spinal.lib.bus.tilelink.Opcode.A.PUT_FULL_DATA, 0xF30)
          
          Should to the trick

**Comment by Dolu1990** [comment] 2024-01-22 08:27
> counter by 7 times more when

Hooo that is right, have to add a check to only count up on the last beat of a burst : 

```scala
add(l2c.rework(l2c.io.down.a.fire && l2c.io.down.a.isLast() && l2c.io.down.a.opcode === spinal.lib.bus.tilelink.Opcode.A.PUT_FULL_DATA), 0xF30)
```

**Comment by Dolu1990** [comment] 2024-01-29 10:16
Hi,

How do you run your code in litex ? i mean, are you sure your code run in the DDR ? and not the on chip ram ?

**Comment by Dolu1990** [comment] 2024-01-29 10:16
Easy way to check it is to check its memory mapping.

**Comment by Dolu1990** [comment] 2024-01-30 14:51
that is curious.
Did you tried to run it in simulation via litex sim ? and check the wave ?

**Comment by Dolu1990** [comment] 2024-01-30 15:14
So, would need to look at the litex sim, to see if there is trafic or not on the l2 cache, to understand if the issue is on the probe side, or the setup side

**Comment by Dolu1990** [comment] 2024-01-30 15:32
By looking at the wave form generated by litex sim, via the args --trace --trace-fst if i remember well.

**Comment by Dolu1990** [comment] 2024-02-05 10:29
Hi,

You need both  --trace and --trace-fst . Without --trace it will not add data to the fst file i think. Then should be good to vew with gtkwave

**Comment by Dolu1990** [comment] 2024-02-06 13:33
You may need to install pyvcd : 
sudo pip install pyvcd

**Closed as completed** 2024-06-14 21:44 UTC
